services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: logio-product-cs-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ..:/var/www
  nginx:
    image: nginx:1.24-alpine
    container_name: logio-product-cs-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ..:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mariadb
    container_name: logio-product-cs-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb/storage:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: logio-product-cs-adminer
    restart: always
    ports:
      - 8080:8080